import CharacterModel from './CharacterModel';

export const starterCharacters: CharacterModel[] = [
  { name: 'Character 1', class: 'Cleric', level: 18 },
  { name: 'Character 2', class: 'Ranger', level: 2 },
  { name: 'Character 3', class: 'Rogue', level: 8 },
  { name: 'Character 4', class: 'Wizard', level: 3 },
  { name: 'Character 5', class: 'Sorcerer', level: 10 },
  { name: 'Character 6', class: 'Thief', level: 14 },
  { name: 'Character 7', class: 'Cleric', level: 6 },
  { name: 'Character 8', class: 'Stalker', level: 6 },
  { name: 'Character 9', class: 'Sorcerer', level: 16 },
  { name: 'Character 10', class: 'Wizard', level: 11 },
  { name: 'Character 11', class: 'Wizard', level: 17 },
  { name: 'Character 12', class: 'Wizard', level: 11 },
  { name: 'Character 13', class: 'Wizard', level: 16 },
  { name: 'Character 14', class: 'Archer', level: 2 },
  { name: 'Character 15', class: 'Thief', level: 3 },
  { name: 'Character 16', class: 'Cleric', level: 16 },
  { name: 'Character 17', class: 'Fighter', level: 7 },
  { name: 'Character 18', class: 'Rogue', level: 11 },
  { name: 'Character 19', class: 'Cleric', level: 15 },
  { name: 'Character 20', class: 'Thief', level: 9 },
  { name: 'Character 21', class: 'Bard', level: 19 },
  { name: 'Character 22', class: 'Rogue', level: 16 },
  { name: 'Character 23', class: 'Sorcerer', level: 7 },
  { name: 'Character 24', class: 'Cleric', level: 2 },
  { name: 'Character 25', class: 'Fighter', level: 5 },
  { name: 'Character 26', class: 'Thief', level: 17 },
  { name: 'Character 27', class: 'Archer', level: 16 },
  { name: 'Character 28', class: 'Wizard', level: 19 },
  { name: 'Character 29', class: 'Thief', level: 6 },
  { name: 'Character 30', class: 'Wizard', level: 7 },
  { name: 'Character 31', class: 'Stalker', level: 9 },
  { name: 'Character 32', class: 'Ranger', level: 4 },
  { name: 'Character 33', class: 'Bard', level: 7 },
  { name: 'Character 34', class: 'Bard', level: 5 },
  { name: 'Character 35', class: 'Archer', level: 6 },
  { name: 'Character 36', class: 'Rogue', level: 18 },
  { name: 'Character 37', class: 'Cleric', level: 6 },
  { name: 'Character 38', class: 'Sorcerer', level: 4 },
  { name: 'Character 39', class: 'Sorcerer', level: 19 },
  { name: 'Character 40', class: 'Archer', level: 2 },
  { name: 'Character 41', class: 'Archer', level: 15 },
  { name: 'Character 42', class: 'Stalker', level: 4 },
  { name: 'Character 43', class: 'Ranger', level: 13 },
  { name: 'Character 44', class: 'Bard', level: 5 },
  { name: 'Character 45', class: 'Sorcerer', level: 20 },
  { name: 'Character 46', class: 'Rogue', level: 10 },
  { name: 'Character 47', class: 'Rogue', level: 16 },
  { name: 'Character 48', class: 'Bard', level: 7 },
  { name: 'Character 49', class: 'Stalker', level: 7 },
  { name: 'Character 50', class: 'Ranger', level: 7 },
  { name: 'Character 51', class: 'Stalker', level: 18 },
  { name: 'Character 52', class: 'Fighter', level: 3 },
  { name: 'Character 53', class: 'Wizard', level: 11 },
  { name: 'Character 54', class: 'Bard', level: 17 },
  { name: 'Character 55', class: 'Archer', level: 14 },
  { name: 'Character 56', class: 'Sorcerer', level: 12 },
  { name: 'Character 57', class: 'Wizard', level: 9 },
  { name: 'Character 58', class: 'Archer', level: 17 },
  { name: 'Character 59', class: 'Wizard', level: 5 },
  { name: 'Character 60', class: 'Cleric', level: 17 },
  { name: 'Character 61', class: 'Cleric', level: 8 },
  { name: 'Character 62', class: 'Rogue', level: 6 },
  { name: 'Character 63', class: 'Sorcerer', level: 10 },
  { name: 'Character 64', class: 'Stalker', level: 14 },
  { name: 'Character 65', class: 'Stalker', level: 7 },
  { name: 'Character 66', class: 'Cleric', level: 10 },
  { name: 'Character 67', class: 'Rogue', level: 17 },
  { name: 'Character 68', class: 'Fighter', level: 14 },
  { name: 'Character 69', class: 'Stalker', level: 5 },
  { name: 'Character 70', class: 'Rogue', level: 3 },
  { name: 'Character 71', class: 'Rogue', level: 17 },
  { name: 'Character 72', class: 'Wizard', level: 13 },
  { name: 'Character 73', class: 'Rogue', level: 17 },
  { name: 'Character 74', class: 'Ranger', level: 15 },
  { name: 'Character 75', class: 'Wizard', level: 9 },
  { name: 'Character 76', class: 'Ranger', level: 11 },
  { name: 'Character 77', class: 'Wizard', level: 5 },
  { name: 'Character 78', class: 'Wizard', level: 4 },
  { name: 'Character 79', class: 'Sorcerer', level: 17 },
  { name: 'Character 80', class: 'Thief', level: 17 },
  { name: 'Character 81', class: 'Bard', level: 9 },
  { name: 'Character 82', class: 'Sorcerer', level: 2 },
  { name: 'Character 83', class: 'Ranger', level: 2 },
  { name: 'Character 84', class: 'Rogue', level: 8 },
  { name: 'Character 85', class: 'Ranger', level: 9 },
  { name: 'Character 86', class: 'Wizard', level: 12 },
  { name: 'Character 87', class: 'Archer', level: 6 },
  { name: 'Character 88', class: 'Sorcerer', level: 13 },
  { name: 'Character 89', class: 'Rogue', level: 8 },
  { name: 'Character 90', class: 'Wizard', level: 19 },
  { name: 'Character 91', class: 'Stalker', level: 6 },
  { name: 'Character 92', class: 'Stalker', level: 10 },
  { name: 'Character 93', class: 'Cleric', level: 9 },
  { name: 'Character 94', class: 'Cleric', level: 19 },
  { name: 'Character 95', class: 'Ranger', level: 8 },
  { name: 'Character 96', class: 'Bard', level: 1 },
  { name: 'Character 97', class: 'Thief', level: 18 },
  { name: 'Character 98', class: 'Bard', level: 13 },
  { name: 'Character 99', class: 'Sorcerer', level: 20 },
  { name: 'Character 100', class: 'Thief', level: 2 },
  { name: 'Character 101', class: 'Cleric', level: 18 },
  { name: 'Character 102', class: 'Ranger', level: 2 },
  { name: 'Character 103', class: 'Rogue', level: 8 },
  { name: 'Character 104', class: 'Wizard', level: 3 },
  { name: 'Character 105', class: 'Sorcerer', level: 10 },
  { name: 'Character 106', class: 'Thief', level: 14 },
  { name: 'Character 107', class: 'Cleric', level: 6 },
  { name: 'Character 108', class: 'Stalker', level: 6 },
  { name: 'Character 109', class: 'Sorcerer', level: 16 },
  { name: 'Character 110', class: 'Wizard', level: 11 },
  { name: 'Character 111', class: 'Wizard', level: 17 },
  { name: 'Character 112', class: 'Wizard', level: 11 },
  { name: 'Character 113', class: 'Wizard', level: 16 },
  { name: 'Character 114', class: 'Archer', level: 2 },
  { name: 'Character 115', class: 'Thief', level: 3 },
  { name: 'Character 116', class: 'Cleric', level: 16 },
  { name: 'Character 117', class: 'Fighter', level: 7 },
  { name: 'Character 118', class: 'Rogue', level: 11 },
  { name: 'Character 119', class: 'Cleric', level: 15 },
  { name: 'Character 120', class: 'Thief', level: 9 },
  { name: 'Character 121', class: 'Bard', level: 19 },
  { name: 'Character 122', class: 'Rogue', level: 16 },
  { name: 'Character 123', class: 'Sorcerer', level: 7 },
  { name: 'Character 124', class: 'Cleric', level: 2 },
  { name: 'Character 125', class: 'Fighter', level: 5 },
  { name: 'Character 126', class: 'Thief', level: 17 },
  { name: 'Character 127', class: 'Archer', level: 16 },
  { name: 'Character 128', class: 'Wizard', level: 19 },
  { name: 'Character 129', class: 'Thief', level: 6 },
  { name: 'Character 130', class: 'Wizard', level: 7 },
  { name: 'Character 131', class: 'Stalker', level: 9 },
  { name: 'Character 132', class: 'Ranger', level: 4 },
  { name: 'Character 133', class: 'Bard', level: 7 },
  { name: 'Character 134', class: 'Bard', level: 5 },
  { name: 'Character 135', class: 'Archer', level: 6 },
  { name: 'Character 136', class: 'Rogue', level: 18 },
  { name: 'Character 137', class: 'Cleric', level: 6 },
  { name: 'Character 138', class: 'Sorcerer', level: 4 },
  { name: 'Character 139', class: 'Sorcerer', level: 19 },
  { name: 'Character 140', class: 'Archer', level: 2 },
  { name: 'Character 141', class: 'Archer', level: 15 },
  { name: 'Character 142', class: 'Stalker', level: 4 },
  { name: 'Character 143', class: 'Ranger', level: 13 },
  { name: 'Character 144', class: 'Bard', level: 5 },
  { name: 'Character 145', class: 'Sorcerer', level: 20 },
  { name: 'Character 146', class: 'Rogue', level: 10 },
  { name: 'Character 147', class: 'Rogue', level: 16 },
  { name: 'Character 148', class: 'Bard', level: 7 },
  { name: 'Character 149', class: 'Stalker', level: 7 },
  { name: 'Character 150', class: 'Ranger', level: 7 },
  { name: 'Character 151', class: 'Stalker', level: 18 },
  { name: 'Character 152', class: 'Fighter', level: 3 },
  { name: 'Character 153', class: 'Wizard', level: 11 },
  { name: 'Character 154', class: 'Bard', level: 17 },
  { name: 'Character 155', class: 'Archer', level: 14 },
  { name: 'Character 156', class: 'Sorcerer', level: 12 },
  { name: 'Character 157', class: 'Wizard', level: 9 },
  { name: 'Character 158', class: 'Archer', level: 17 },
  { name: 'Character 159', class: 'Wizard', level: 5 },
  { name: 'Character 160', class: 'Cleric', level: 17 },
  { name: 'Character 161', class: 'Cleric', level: 8 },
  { name: 'Character 162', class: 'Rogue', level: 6 },
  { name: 'Character 163', class: 'Sorcerer', level: 10 },
  { name: 'Character 164', class: 'Stalker', level: 14 },
  { name: 'Character 165', class: 'Stalker', level: 7 },
  { name: 'Character 166', class: 'Cleric', level: 10 },
  { name: 'Character 167', class: 'Rogue', level: 17 },
  { name: 'Character 168', class: 'Fighter', level: 14 },
  { name: 'Character 169', class: 'Stalker', level: 5 },
  { name: 'Character 170', class: 'Rogue', level: 3 },
  { name: 'Character 171', class: 'Rogue', level: 17 },
  { name: 'Character 172', class: 'Wizard', level: 13 },
  { name: 'Character 173', class: 'Rogue', level: 17 },
  { name: 'Character 174', class: 'Ranger', level: 15 },
  { name: 'Character 175', class: 'Wizard', level: 9 },
  { name: 'Character 176', class: 'Ranger', level: 11 },
  { name: 'Character 177', class: 'Wizard', level: 5 },
  { name: 'Character 178', class: 'Wizard', level: 4 },
  { name: 'Character 179', class: 'Sorcerer', level: 17 },
  { name: 'Character 180', class: 'Thief', level: 17 },
  { name: 'Character 181', class: 'Bard', level: 9 },
  { name: 'Character 182', class: 'Sorcerer', level: 2 },
  { name: 'Character 183', class: 'Ranger', level: 2 },
  { name: 'Character 184', class: 'Rogue', level: 8 },
  { name: 'Character 185', class: 'Ranger', level: 9 },
  { name: 'Character 186', class: 'Wizard', level: 12 },
  { name: 'Character 187', class: 'Archer', level: 6 },
  { name: 'Character 188', class: 'Sorcerer', level: 13 },
  { name: 'Character 189', class: 'Rogue', level: 8 },
  { name: 'Character 190', class: 'Wizard', level: 19 },
  { name: 'Character 191', class: 'Stalker', level: 6 },
  { name: 'Character 192', class: 'Stalker', level: 10 },
  { name: 'Character 193', class: 'Cleric', level: 9 },
  { name: 'Character 194', class: 'Cleric', level: 19 },
  { name: 'Character 195', class: 'Ranger', level: 8 },
  { name: 'Character 196', class: 'Bard', level: 1 },
  { name: 'Character 197', class: 'Thief', level: 18 },
  { name: 'Character 198', class: 'Bard', level: 13 },
  { name: 'Character 199', class: 'Sorcerer', level: 20 },
  { name: 'Character 200', class: 'Thief', level: 2 },
  { name: 'Character 201', class: 'Rogue', level: 9 },
  { name: 'Character 202', class: 'Cleric', level: 16 },
  { name: 'Character 203', class: 'Fighter', level: 12 },
  { name: 'Character 204', class: 'Rogue', level: 20 },
  // { name: "Character 205", class: "Rogue", level: 16 },
  // { name: "Character 206", class: "Bard", level: 10 },
  // { name: "Character 207", class: "Archer", level: 1 },
  // { name: "Character 208", class: "Stalker", level: 6 },
  // { name: "Character 209", class: "Stalker", level: 17 },
  // { name: "Character 210", class: "Ranger", level: 14 },
  // { name: "Character 211", class: "Thief", level: 12 },
  // { name: "Character 212", class: "Sorcerer", level: 14 },
  // { name: "Character 213", class: "Fighter", level: 4 },
  // { name: "Character 214", class: "Bard", level: 16 },
  // { name: "Character 215", class: "Sorcerer", level: 15 },
  // { name: "Character 216", class: "Sorcerer", level: 14 },
  // { name: "Character 217", class: "Bard", level: 14 },
  // { name: "Character 218", class: "Ranger", level: 15 },
  // { name: "Character 219", class: "Thief", level: 15 },
  // { name: "Character 220", class: "Archer", level: 16 },
  // { name: "Character 221", class: "Rogue", level: 5 },
  // { name: "Character 222", class: "Cleric", level: 17 },
  // { name: "Character 223", class: "Rogue", level: 17 },
  // { name: "Character 224", class: "Wizard", level: 4 },
  // { name: "Character 225", class: "Fighter", level: 17 },
  // { name: "Character 226", class: "Bard", level: 7 },
  // { name: "Character 227", class: "Fighter", level: 18 },
  // { name: "Character 228", class: "Fighter", level: 1 },
  // { name: "Character 229", class: "Sorcerer", level: 3 },
  // { name: "Character 230", class: "Sorcerer", level: 19 },
  // { name: "Character 231", class: "Ranger", level: 10 },
  // { name: "Character 232", class: "Cleric", level: 15 },
  // { name: "Character 233", class: "Rogue", level: 18 },
  // { name: "Character 234", class: "Rogue", level: 12 },
  // { name: "Character 235", class: "Wizard", level: 20 },
  // { name: "Character 236", class: "Cleric", level: 4 },
  // { name: "Character 237", class: "Fighter", level: 11 },
  // { name: "Character 238", class: "Thief", level: 13 },
  // { name: "Character 239", class: "Stalker", level: 12 },
  // { name: "Character 240", class: "Thief", level: 8 },
  // { name: "Character 241", class: "Ranger", level: 20 },
  // { name: "Character 242", class: "Sorcerer", level: 2 },
  // { name: "Character 243", class: "Archer", level: 1 },
  // { name: "Character 244", class: "Ranger", level: 9 },
  // { name: "Character 245", class: "Wizard", level: 15 },
  // { name: "Character 246", class: "Archer", level: 8 },
  // { name: "Character 247", class: "Ranger", level: 15 },
  // { name: "Character 248", class: "Rogue", level: 7 },
  // { name: "Character 249", class: "Ranger", level: 12 },
  // { name: "Character 250", class: "Fighter", level: 19 },
  // { name: "Character 251", class: "Bard", level: 20 },
  // { name: "Character 252", class: "Bard", level: 8 },
  // { name: "Character 253", class: "Thief", level: 6 },
  // { name: "Character 254", class: "Thief", level: 11 },
  // { name: "Character 255", class: "Sorcerer", level: 19 },
  // { name: "Character 256", class: "Sorcerer", level: 14 },
  // { name: "Character 257", class: "Sorcerer", level: 6 },
  // { name: "Character 258", class: "Sorcerer", level: 1 },
  // { name: "Character 259", class: "Rogue", level: 9 },
  // { name: "Character 260", class: "Sorcerer", level: 2 },
  // { name: "Character 261", class: "Bard", level: 11 },
  // { name: "Character 262", class: "Cleric", level: 10 },
  // { name: "Character 263", class: "Rogue", level: 11 },
  // { name: "Character 264", class: "Stalker", level: 18 },
  // { name: "Character 265", class: "Wizard", level: 11 },
  // { name: "Character 266", class: "Fighter", level: 17 },
  // { name: "Character 267", class: "Thief", level: 5 },
  // { name: "Character 268", class: "Ranger", level: 18 },
  // { name: "Character 269", class: "Thief", level: 20 },
  // { name: "Character 270", class: "Wizard", level: 4 },
  // { name: "Character 271", class: "Bard", level: 2 },
  // { name: "Character 272", class: "Ranger", level: 5 },
  // { name: "Character 273", class: "Cleric", level: 10 },
  // { name: "Character 274", class: "Thief", level: 8 },
  // { name: "Character 275", class: "Thief", level: 9 },
  // { name: "Character 276", class: "Rogue", level: 16 },
  // { name: "Character 277", class: "Stalker", level: 15 },
  // { name: "Character 278", class: "Thief", level: 3 },
  // { name: "Character 279", class: "Archer", level: 20 },
  // { name: "Character 280", class: "Stalker", level: 8 },
  // { name: "Character 281", class: "Stalker", level: 13 },
  // { name: "Character 282", class: "Wizard", level: 14 },
  // { name: "Character 283", class: "Fighter", level: 7 },
  // { name: "Character 284", class: "Sorcerer", level: 20 },
  // { name: "Character 285", class: "Bard", level: 13 },
  // { name: "Character 286", class: "Archer", level: 10 },
  // { name: "Character 287", class: "Sorcerer", level: 19 },
  // { name: "Character 288", class: "Thief", level: 15 },
  // { name: "Character 289", class: "Cleric", level: 15 },
  // { name: "Character 290", class: "Cleric", level: 9 },
  // { name: "Character 291", class: "Rogue", level: 12 },
  // { name: "Character 292", class: "Sorcerer", level: 4 },
  // { name: "Character 293", class: "Cleric", level: 8 },
  // { name: "Character 294", class: "Wizard", level: 3 },
  // { name: "Character 295", class: "Rogue", level: 19 },
  // { name: "Character 296", class: "Ranger", level: 3 },
  // { name: "Character 297", class: "Cleric", level: 5 },
  // { name: "Character 298", class: "Thief", level: 19 },
  // { name: "Character 299", class: "Fighter", level: 14 },
  // { name: "Character 300", class: "Bard", level: 3 },
  // { name: "Character 301", class: "Rogue", level: 9 },
  // { name: "Character 302", class: "Cleric", level: 16 },
  // { name: "Character 303", class: "Fighter", level: 12 },
  // { name: "Character 304", class: "Rogue", level: 20 },
  // { name: "Character 305", class: "Rogue", level: 16 },
  // { name: "Character 306", class: "Bard", level: 10 },
  // { name: "Character 307", class: "Archer", level: 1 },
  // { name: "Character 308", class: "Stalker", level: 6 },
  // { name: "Character 309", class: "Stalker", level: 17 },
  // { name: "Character 310", class: "Ranger", level: 14 },
  // { name: "Character 311", class: "Thief", level: 12 },
  // { name: "Character 312", class: "Sorcerer", level: 14 },
  // { name: "Character 313", class: "Fighter", level: 4 },
  // { name: "Character 314", class: "Bard", level: 16 },
  // { name: "Character 315", class: "Sorcerer", level: 15 },
  // { name: "Character 316", class: "Sorcerer", level: 14 },
  // { name: "Character 317", class: "Bard", level: 14 },
  // { name: "Character 318", class: "Ranger", level: 15 },
  // { name: "Character 319", class: "Thief", level: 15 },
  // { name: "Character 320", class: "Archer", level: 16 },
  // { name: "Character 321", class: "Rogue", level: 5 },
  // { name: "Character 322", class: "Cleric", level: 17 },
  // { name: "Character 323", class: "Rogue", level: 17 },
  // { name: "Character 324", class: "Wizard", level: 4 },
  // { name: "Character 325", class: "Fighter", level: 17 },
  // { name: "Character 326", class: "Bard", level: 7 },
  // { name: "Character 327", class: "Fighter", level: 18 },
  // { name: "Character 328", class: "Fighter", level: 1 },
  // { name: "Character 329", class: "Sorcerer", level: 3 },
  // { name: "Character 330", class: "Sorcerer", level: 19 },
  // { name: "Character 331", class: "Ranger", level: 10 },
  // { name: "Character 332", class: "Cleric", level: 15 },
  // { name: "Character 333", class: "Rogue", level: 18 },
  // { name: "Character 334", class: "Rogue", level: 12 },
  // { name: "Character 335", class: "Wizard", level: 20 },
  // { name: "Character 336", class: "Cleric", level: 4 },
  // { name: "Character 337", class: "Fighter", level: 11 },
  // { name: "Character 338", class: "Thief", level: 13 },
  // { name: "Character 339", class: "Stalker", level: 12 },
  // { name: "Character 340", class: "Thief", level: 8 },
  // { name: "Character 341", class: "Ranger", level: 20 },
  // { name: "Character 342", class: "Sorcerer", level: 2 },
  // { name: "Character 343", class: "Archer", level: 1 },
  // { name: "Character 344", class: "Ranger", level: 9 },
  // { name: "Character 345", class: "Wizard", level: 15 },
  // { name: "Character 346", class: "Archer", level: 8 },
  // { name: "Character 347", class: "Ranger", level: 15 },
  // { name: "Character 348", class: "Rogue", level: 7 },
  // { name: "Character 349", class: "Ranger", level: 12 },
  // { name: "Character 350", class: "Fighter", level: 19 },
  // { name: "Character 351", class: "Bard", level: 20 },
  // { name: "Character 352", class: "Bard", level: 8 },
  // { name: "Character 353", class: "Thief", level: 6 },
  // { name: "Character 354", class: "Thief", level: 11 },
  // { name: "Character 355", class: "Sorcerer", level: 19 },
  // { name: "Character 356", class: "Sorcerer", level: 14 },
  // { name: "Character 357", class: "Sorcerer", level: 6 },
  // { name: "Character 358", class: "Sorcerer", level: 1 },
  // { name: "Character 359", class: "Rogue", level: 9 },
  // { name: "Character 360", class: "Sorcerer", level: 2 },
  // { name: "Character 361", class: "Bard", level: 11 },
  // { name: "Character 362", class: "Cleric", level: 10 },
  // { name: "Character 363", class: "Rogue", level: 11 },
  // { name: "Character 364", class: "Stalker", level: 18 },
  // { name: "Character 365", class: "Wizard", level: 11 },
  // { name: "Character 366", class: "Fighter", level: 17 },
  // { name: "Character 367", class: "Thief", level: 5 },
  // { name: "Character 368", class: "Ranger", level: 18 },
  // { name: "Character 369", class: "Thief", level: 20 },
  // { name: "Character 370", class: "Wizard", level: 4 },
  // { name: "Character 371", class: "Bard", level: 2 },
  // { name: "Character 372", class: "Ranger", level: 5 },
  // { name: "Character 373", class: "Cleric", level: 10 },
  // { name: "Character 374", class: "Thief", level: 8 },
  // { name: "Character 375", class: "Thief", level: 9 },
  // { name: "Character 376", class: "Rogue", level: 16 },
  // { name: "Character 377", class: "Stalker", level: 15 },
  // { name: "Character 378", class: "Thief", level: 3 },
  // { name: "Character 379", class: "Archer", level: 20 },
  // { name: "Character 380", class: "Stalker", level: 8 },
  // { name: "Character 381", class: "Stalker", level: 13 },
  // { name: "Character 382", class: "Wizard", level: 14 },
  // { name: "Character 383", class: "Fighter", level: 7 },
  // { name: "Character 384", class: "Sorcerer", level: 20 },
  // { name: "Character 385", class: "Bard", level: 13 },
  // { name: "Character 386", class: "Archer", level: 10 },
  // { name: "Character 387", class: "Sorcerer", level: 19 },
  // { name: "Character 388", class: "Thief", level: 15 },
  // { name: "Character 389", class: "Cleric", level: 15 },
  // { name: "Character 390", class: "Cleric", level: 9 },
  // { name: "Character 391", class: "Rogue", level: 12 },
  // { name: "Character 392", class: "Sorcerer", level: 4 },
  // { name: "Character 393", class: "Cleric", level: 8 },
  // { name: "Character 394", class: "Wizard", level: 3 },
  // { name: "Character 395", class: "Rogue", level: 19 },
  // { name: "Character 396", class: "Ranger", level: 3 },
  // { name: "Character 397", class: "Cleric", level: 5 },
  // { name: "Character 398", class: "Thief", level: 19 },
  // { name: "Character 399", class: "Fighter", level: 14 },
  // { name: "Character 400", class: "Bard", level: 3 },
  // { name: "Character 401", class: "Rogue", level: 9 },
  // { name: "Character 402", class: "Cleric", level: 16 },
  // { name: "Character 403", class: "Fighter", level: 12 },
  // { name: "Character 404", class: "Rogue", level: 20 },
  // { name: "Character 405", class: "Rogue", level: 16 },
  // { name: "Character 406", class: "Bard", level: 10 },
  // { name: "Character 407", class: "Archer", level: 1 },
  // { name: "Character 408", class: "Stalker", level: 6 },
  // { name: "Character 409", class: "Stalker", level: 17 },
  // { name: "Character 410", class: "Ranger", level: 14 },
  // { name: "Character 411", class: "Thief", level: 12 },
  // { name: "Character 412", class: "Sorcerer", level: 14 },
  // { name: "Character 413", class: "Fighter", level: 4 },
  // { name: "Character 414", class: "Bard", level: 16 },
  // { name: "Character 415", class: "Sorcerer", level: 15 },
  // { name: "Character 416", class: "Sorcerer", level: 14 },
  // { name: "Character 417", class: "Bard", level: 14 },
  // { name: "Character 418", class: "Ranger", level: 15 },
  // { name: "Character 419", class: "Thief", level: 15 },
  // { name: "Character 420", class: "Archer", level: 16 },
  // { name: "Character 421", class: "Rogue", level: 5 },
  // { name: "Character 422", class: "Cleric", level: 17 },
  // { name: "Character 423", class: "Rogue", level: 17 },
  // { name: "Character 424", class: "Wizard", level: 4 },
  // { name: "Character 425", class: "Fighter", level: 17 },
  // { name: "Character 426", class: "Bard", level: 7 },
  // { name: "Character 427", class: "Fighter", level: 18 },
  // { name: "Character 428", class: "Fighter", level: 1 },
  // { name: "Character 429", class: "Sorcerer", level: 3 },
  // { name: "Character 430", class: "Sorcerer", level: 19 },
  // { name: "Character 431", class: "Ranger", level: 10 },
  // { name: "Character 432", class: "Cleric", level: 15 },
  // { name: "Character 433", class: "Rogue", level: 18 },
  // { name: "Character 434", class: "Rogue", level: 12 },
  // { name: "Character 435", class: "Wizard", level: 20 },
  // { name: "Character 436", class: "Cleric", level: 4 },
  // { name: "Character 437", class: "Fighter", level: 11 },
  // { name: "Character 438", class: "Thief", level: 13 },
  // { name: "Character 439", class: "Stalker", level: 12 },
  // { name: "Character 440", class: "Thief", level: 8 },
  // { name: "Character 441", class: "Ranger", level: 20 },
  // { name: "Character 442", class: "Sorcerer", level: 2 },
  // { name: "Character 443", class: "Archer", level: 1 },
  // { name: "Character 444", class: "Ranger", level: 9 },
  // { name: "Character 445", class: "Wizard", level: 15 },
  // { name: "Character 446", class: "Archer", level: 8 },
  // { name: "Character 447", class: "Ranger", level: 15 },
  // { name: "Character 448", class: "Rogue", level: 7 },
  // { name: "Character 449", class: "Ranger", level: 12 },
  // { name: "Character 450", class: "Fighter", level: 19 },
  // { name: "Character 451", class: "Bard", level: 20 },
  // { name: "Character 452", class: "Bard", level: 8 },
  // { name: "Character 453", class: "Thief", level: 6 },
  // { name: "Character 454", class: "Thief", level: 11 },
  // { name: "Character 455", class: "Sorcerer", level: 19 },
  // { name: "Character 456", class: "Sorcerer", level: 14 },
  // { name: "Character 457", class: "Sorcerer", level: 6 },
  // { name: "Character 458", class: "Sorcerer", level: 1 },
  // { name: "Character 459", class: "Rogue", level: 9 },
  // { name: "Character 460", class: "Sorcerer", level: 2 },
  // { name: "Character 461", class: "Bard", level: 11 },
  // { name: "Character 462", class: "Cleric", level: 10 },
  // { name: "Character 463", class: "Rogue", level: 11 },
  // { name: "Character 464", class: "Stalker", level: 18 },
  // { name: "Character 465", class: "Wizard", level: 11 },
  // { name: "Character 466", class: "Fighter", level: 17 },
  // { name: "Character 467", class: "Thief", level: 5 },
  // { name: "Character 468", class: "Ranger", level: 18 },
  // { name: "Character 469", class: "Thief", level: 20 },
  // { name: "Character 470", class: "Wizard", level: 4 },
  // { name: "Character 471", class: "Bard", level: 2 },
  // { name: "Character 472", class: "Ranger", level: 5 },
  // { name: "Character 473", class: "Cleric", level: 10 },
  // { name: "Character 474", class: "Thief", level: 8 },
  // { name: "Character 475", class: "Thief", level: 9 },
  // { name: "Character 476", class: "Rogue", level: 16 },
  // { name: "Character 477", class: "Stalker", level: 15 },
  // { name: "Character 478", class: "Thief", level: 3 },
  // { name: "Character 479", class: "Archer", level: 20 },
  // { name: "Character 480", class: "Stalker", level: 8 },
  // { name: "Character 481", class: "Stalker", level: 13 },
  // { name: "Character 482", class: "Wizard", level: 14 },
  // { name: "Character 483", class: "Fighter", level: 7 },
  // { name: "Character 484", class: "Sorcerer", level: 20 },
  // { name: "Character 485", class: "Bard", level: 13 },
  // { name: "Character 486", class: "Archer", level: 10 },
  // { name: "Character 487", class: "Sorcerer", level: 19 },
  // { name: "Character 488", class: "Thief", level: 15 },
  // { name: "Character 489", class: "Cleric", level: 15 },
  // { name: "Character 490", class: "Cleric", level: 9 },
  // { name: "Character 491", class: "Rogue", level: 12 },
  // { name: "Character 492", class: "Sorcerer", level: 4 },
  // { name: "Character 493", class: "Cleric", level: 8 },
  // { name: "Character 494", class: "Wizard", level: 3 },
  // { name: "Character 495", class: "Rogue", level: 19 },
  // { name: "Character 496", class: "Ranger", level: 3 },
  // { name: "Character 497", class: "Cleric", level: 5 },
  // { name: "Character 498", class: "Thief", level: 19 },
  // { name: "Character 499", class: "Fighter", level: 14 },
  // { name: "Character 500", class: "Bard", level: 3 },
];
